# Count the number of each gene type

PREFIX ncbio: <https://dbcls.github.io/ncbigene-rdf/ontology.ttl#>

SELECT (COUNT(?s) AS ?count) ?type
WHERE {
  ?s ncbio:typeOfGene ?type .
}
ORDER BY DESC(?count)
