#!/usr/bin/env spang2
# @endpoint https://orth.dbcls.jp/sparql-proxy
# @option -ac

PREFIX : <http://purl.org/orthordf/ontology#>

SELECT (COUNT(DISTINCT ?gene) AS ?count) ?cat ?go ?label
FROM <http://purl.obolibrary.org/obo/go.owl>
FROM <http://purl.org/orthordf/gene2go/>
FROM <https://orth.dbcls.jp/rdf/resource/Homo_sapiens.gene_info>
WHERE {
  ?gene :taxid taxid:9606 ;
        :gene2go ?go .
  OPTIONAL {
    ?go rdfs:label ?label .
  }
  ?gene :hasGOAnnotation [
        :hasGO ?go ;
        :category ?cat ] .
  OPTIONAL {
    ?gene rdfs:label ?gene_label .
  }
}
ORDER BY DESC(?count)
