#!/usr/bin/env spang2
# @endpoint https://spang.dbcls.jp/sparql
# @option -a

PREFIX orth: <http://purl.org/net/orth#>
PREFIX taxid: <http://identifiers.org/taxonomy/>

SELECT *
WHERE {
  ?gene1 orth:hasOrtholog ?gene2 .
  ?gene1 orth:taxon taxid:7955 .
  ?gene2 orth:taxon taxid:8090 .
}
