#!/usr/bin/env spang2
# @endpoint orth2
# @option -ac

PREFIX : <http://purl.org/orthordf/ontology#>

SELECT (COUNT(DISTINCT ?gene) AS ?count) ?taxid ?label (group_concat(distinct ?common; separator=", ") as ?group) ?common2
WHERE {
  ?gene :taxid ?taxid .
  ?taxid rdfs:label ?label .
  OPTIONAL {
    ?taxid taxon:commonName ?common .
  }
  OPTIONAL {
    ?taxid taxon:genbankCommonName ?common2 .
  }
}
ORDER BY DESC(?count)
